# Adobe Experience Manager (AEM) Instance.
# AEM quickstart runs directly from command line with embedded Jetty Servlet Container.

variants:
- variant: aem-author
- variant: aem-publish

templateDir: sample-aem-cms

files:

# AEM OSGi System Configuration
- file: sample-aem-cms-config.provisioning
  dir: packages
  template: sample-aem-cms-config.provisioning.hbs
  postProcessors:
  - aem-contentpackage-osgiconfig
  postProcessorOptions:
    contentPackage:
      name: sample-aem-cms-config
      rootPath: /apps/sample-aem-cms-config/config
      filters:
      - filter: /apps/sample-aem-cms-config

# AEM Systems users with ACLs (Author)
- file: sample-aem-cms-systemusers.json
  dir: packages
  template: sample-aem-cms-systemusers.json.hbs
  postProcessors:
  - aem-contentpackage
  postProcessorOptions:
    contentPackage:
      name: sample-aem-cms-author-systemusers
      acHandling: merge
      rootPath: /
      filters:
      - filter: /content/rep:policy
      - filter: /conf/rep:policy
      - filter: /apps/conf/rep:policy
      - filter: /libs/conf/rep:policy
      - filter: /home/users/system/sling-caconfig



# Defines configuration parameters and default values
config:
  contentPackage:
    group: wcm-io-sample
    version: "${version}"

  # Log levels
  log:
    logPath: "logs"
    projectSpecifcLogLevel: warn


  # Example for config override configuration
  #configOverrides:
  #  "/path/to/config/scope":
  #    siteUrl:
  #    siteUrlSecure:
  #    siteUrlAuthor:
