# Define application-specific AEM packages downloaded from Maven Repository.

files:

# Application package
- url: mvn:io.wcm/io.wcm.caconfig.sample-app.complete//zip
  dir: packages

# Application sample content package
- url: mvn:io.wcm/io.wcm.caconfig.sample-app.sample-content//zip
  dir: packages
  condition: ${sampleContent}


# Defines configuration parameters and default values
config:
  sampleContent: false
