# Context-Aware Configuration Sample Application

# Inherit default AEM functionality from "AEM Definitions", see http://devops.wcm.io/conga/definitions/aem/
inherits:
- role: aem-cms

variants:
- variant: aem-author
- variant: aem-publish

templateDir: sample-aem-cms

files:

# AEM OSGi System Configuration
- file: sample-aem-cms-config.provisioning
  dir: packages
  template: sample-aem-cms-config.provisioning.hbs
  postProcessors:
  - aem-contentpackage-osgiconfig
  postProcessorOptions:
    contentPackage:
      name: sample-aem-cms-config
      rootPath: /apps/sample-aem-cms-config/config
      filters:
      - filter: /apps/sample-aem-cms-config

# AEM Systems users with ACLs (Author)
- file: sample-aem-cms-systemusers.json
  dir: packages
  template: sample-aem-cms-systemusers.json.hbs
  postProcessors:
  - aem-contentpackage
  postProcessorOptions:
    contentPackage:
      name: sample-aem-cms-author-systemusers
      acHandling: merge
      rootPath: /
      filters:
      - filter: /content/rep:policy
      - filter: /conf/rep:policy
      - filter: /apps/conf/rep:policy
      - filter: /libs/conf/rep:policy
      - filter: /home/users/system/sling-caconfig

# Application package
- url: mvn:io.wcm/io.wcm.caconfig.sample-app.complete//zip
  dir: packages

# Application sample content package
- url: mvn:io.wcm/io.wcm.caconfig.sample-app.sample-content-default//zip
  dir: packages
  condition: ${app.sampleContent}


# Defines configuration parameters and default values
config:
  contentPackage:
    group: wcm-io-sample
    version: "${version}"

  app:
    sampleContent: false
    caconfigAemPagePersistence: false


  # Example for config override configuration
  #configOverrides:
  #  "/path/to/config/scope":
  #    siteUrl:
  #    siteUrlSecure:
  #    siteUrlAuthor:
